### ISSUE TITLE
Add an option in Camptix setting to enable invoicing

### ISSUE THREAD

**Issue by iceablemedia** [wceu/camptix-invoices#1]
* Add an option in Camptix settings to enable invoicing (probably leave it "off" by default)

We mean this plugin to be installed on a multisite instance, so we wouldn't want to force it to be enabled by default for every site.
Also every site admin wouldn't want this to be enabled until they set some basic options such as logo and company information to add to each invoice.

**Comment by avillegasn** [comment]
> We mean this plugin to be installed on a multisite instance, so we wouldn't want to force it to be enabled by default for every site.

The plugin could be installed but not "network activated" by default. Thus, every site admin in the multisite could decide whether to activate it or not on his/her site.

> Also every site admin wouldn't want this to be enabled until they set some basic options such as logo and company information to add to each invoice.

Then we should add an extra setting to enable the requests from ticket purchasers. When enabled, users that purchase a ticket will be able to ask for an invoice. When disabled, the "I need an invoice" form field won't appear in the process to purchase tickets.
