### ISSUE TITLE
Format invoice to mimic current styles

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#12]
We need to create a `template-invoice.php` file with the proper styles WordCamp Europe uses.

**Comment by avillegasn** [comment]
It is more complex than I thought. We'll need to make changes to the file [facturePDF.php](https://github.com/wceu/camptix-invoices/blob/master/includes/lib/fpdf/facturePDF.php).

This file has a lot of comments in French. I'll need your help here @iceablemedia 🇫🇷 👍 

We'll probably also change the name of the file to invoicePDF.php and fix its references in the code accordingly.

Meanwhile, I'll try to further investigate how the library FPDF works...

**Comment by avillegasn** [comment]
Commit b06fa85ba32853803b980efeaae1eb9b1ddd8841 works on the restyling of the default invoice template. We can close the issue when the translation of comments in French is finished.

**Comment by avillegasn** [comment]
Current invoice template:

<img width="567" alt="captura de pantalla 2019-01-10 a las 12 43 36" src="https://user-images.githubusercontent.com/2486539/50966529-78df4b00-14d5-11e9-9522-0674e799ca0d.png">

**Comment by iceablemedia** [comment]
Comments translated in 8685b555971632a7d40fef7894e63f3076edd122 and file renamed in 290a87b9f2445790a51c8a72b5452e57195dd87c.

The invoice looks great :+1: I guess this issue can be closed.
