### ISSUE TITLE
Remove email in the invoice form when purchasing a ticket 

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#13]
When the person that purchases a ticket needs an invoice, we ask for the email where he/she wants the invoice to be sent. We need to remove that field in the form and send the invoice directly to the email of the person that purchases the ticket.

**Comment by iceablemedia** [comment]
Detail to keep in mind: when buying multiple ticket, the buyer is asked for name + email address for each ticket.

We may send the invoice to the first email address, but this should be made clear. For example, if more than one ticket are being bought, display a note such as "the invoice will be sent to the email address of the first attendee registered above".

**Comment by avillegasn** [comment]
Thinking about this issue again...

Do we really need to remove the email field? I believe the use case where someone buys several tickets on behalf of others is still valid. On that scenario, having the possibility of typing a billing email where to send the invoice (what we have now) seems better than sending the invoice to the first email address.

Maybe this issue needs further discussion...

**Comment by avillegasn** [comment]
No further action
