### ISSUE TITLE
Provide a way for purchasers to recover their invoice

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#14]
It may be the case that some purchasers lose the email with the invoice and want to recover it. We could include a way to download the invoice in the Attendee "Edit information" page.

This needs further discussion.

**Comment by avillegasn** [comment]
Attendees and invoices are not related right now. Given an attendee, we don't know his invoice ID, because an invoice may include more than one ticket (several attendees).

Maybe we should force invoices to be individual (one ticket, one invoice). But this may require several changes in the code.

Another possibility: if a ticket buyer loses the email with the invoice, he/she should contact us by email directly. Probably the amount of people losing these emails would be minimal...

**Comment by mburridge** [comment]
Forcing the invoice to be on an individual per ticket basis would probably require consent from WordCamp Central. We can't unilaterally make that decision.

I agree with your second possibility.

**Comment by iceablemedia** [comment]
+1 for the second possibility.

Additionally, forcing one invoice per ticket would be quite a hassle for companies buying a handful (or more) tickets.

**Comment by iceablemedia** [comment]
> Attendees and invoices are not related right now. Given an attendee, we don't know his invoice ID, because an invoice may include more than one ticket (several attendees).

Given a ticket/attendee, we have a transaction number, which allows to retrieve the invoice for the relevant transaction with a custom query (invoices now also have the transaction ID in a post meta).

However, this does not fully answer the concerns for transactions that include multiple tickets. If we make an invoice available in the "edit ticket" area for each attendee, then every attendee with a ticket from a grouped purchase would have access to the invoice for the whole transaction.

Just sending the invoice by email, and letting attendee ask for a copy if they lose this email, definitely sounds like the easiest solution for now.

**Comment by avillegasn** [comment]
No further action
