### ISSUE TITLE
Apply refactors to the code to follow WordPress programming guidelines

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#15]
Some code fragments still need refactors in order to follow the WordPress programming guidelines. We'll need to perform these changes for the plugin to be accepted to be part of a WordCamp installation. I've no idea on how severe the reviewers will be.

**Comment by iceablemedia** [comment]
I ran an automated pass of WPCS fixes with `phpcbf` in 86b1ebed5a76acc57ff85daf5152630123f9e995

The entire code can certainly benefit from a further manual inspection though.

**Comment by avillegasn** [comment]
Well done. We can wait for the comments of the developers from WordCamp Central (or whoever has to review the plugin) and then fix what needs to be fixed.

**Comment by iandunn** [comment]
We've got a custom PHPCS config that may be helpful here:

https://github.com/WordPress/wordcamp.org/blob/master/phpcs.xml.dist

It's mostly just tweaks to the Core standards, though, so if you've already fixed all of those, then the remaining _style_ issues are probably minor. There may be some important _security_ / _best practices_ issues that PHPCS can identify, though.
