### ISSUE TITLE
Create a Test Procedure Document

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#17]
Define testing scenarios for the camptix-invoices plugin in a document so that it helps other members of the development team to test and cover the functionalities provided by the plugin.

**Comment by iceablemedia** [comment]
As decided during today's AS Team meeting, this will be worked on in this Google document: 
https://docs.google.com/document/d/1FlnxixYn64RtlpWB-3MuNpXGkB8ZlTYxbD7etwChRXo/edit
