### ISSUE TITLE
[Blocker] Use the PDF library already present in the WordCamp.org codebase

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#20]
There is already a [PDF library](https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/plugins/wordcamp-docs/classes/class-wordcamp-docs-pdf-generator.php ) present in WordCamp.org codebase which is maintained and periodically reviewed for security and bug fixes. 
We should switch this plugin to use that library to prevent redundant effort of maintaining two different libraries that does the same job.

**Comment by avillegasn** [comment]
Do we need to create our own class similar to the one you linked but for the invoices (internally using `wkhtmltopdf`)? Or do we need to use `WordCamp_Docs_PDF_Generator` directly?

**Comment by vedanshujain** [comment]
You can directly use `WordCamp_Docs_PDF_Generator` if that does not cause any issues. You can assume that plugin `wordcamp_docs` that this class is part of, will be enabled for all WordCamps that will have camptix-invoices plugin.

**Comment by iandunn** [comment]
Yeah, `WordCamp_Docs_PDF_Generator` will probably become a more generic PDF wrapper in the future. Let us know if you run into any problems using it because it isn't generic enough, and we can help to make it more generic.

**Comment by iceablemedia** [comment]
Like CampTix itself this plugin it is mainly meant for WordCamps but also to be available for use on other sites.

If we use a library that already exists on wordcamp.org, we should provide a fallback in case it doesn't  so the plugin can also work outside of wordcamp.org.

A simple solution would be to bundle a copy of [`class-wordcamp-docs-pdf-generator.php`](https://github.com/kovshenin/wordcamp-docs/blob/master/classes/class-wordcamp-docs-pdf-generator.php) to use in case it is not available, as in:

```
if ( ! class_exists( 'WordCamp_Docs_PDF_Generator' ) {
    require( 'class-wordcamp-docs-pdf-generator.php' );
}
```

and mention in the doc that `wkhtmltopdf` is required on the server for the plugin to work properly.

**Comment by avillegasn** [comment]
383160487434fdeda17f461230a8f66b9dbe6a0a uses wkhtmltopdf as required.

**Comment by iandunn** [comment]
It doesn't seem like including `class-wordcamp-docs-pdf-generator.php` provides a meaningful fallback, since it still wouldn't work if `wkhtmltopdf` is missing.

I don't personally see think it's worth the extra effort to build the plugin for non-wordcamp users, though. Keeping it custom is simpler, removes the support burden, removes back-compat considerations, allows the code to be leaner, and avoids having to keep that file in sync w/ the canonical one.

**Comment by avillegasn** [comment]
Now _WordCamp_Docs_PDF_Generator_ class is not included. I added instructions in the readme file about the explicit dependencies that this plugin requires.

**Comment by iandunn** [comment]
👍
