### ISSUE TITLE
[Suggestion] We should allow marking an invoice as cancelled and refunded.

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#22]
There should be a meta field, or ideally post_status to allow marking an invoice as cancelled or refunded. This will make the data in all places consistent.

**Comment by avillegasn** [comment]
I like the suggestion of using custom post statuses for this scenario. However, since [Gutenberg does not support them (yet?)](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/feature-custom-post-statuses.md), do we need to go this way or just use a meta field?

**Comment by avillegasn** [comment]
4b2ccdce44ff55e6d51f3f5082e3cc14d9b76936 adds basic support for the required custom post statuses.
