### ISSUE TITLE
Unit quantity field is null when invoice is generated directly

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#31]
Unit quantity field in generated invoice PDF is null when invoice is generated directly. Possibly because of https://github.com/wceu/camptix-invoices/blob/master/includes/views/invoice-template.php#L176. This line tries to get the CampTix ticket this invoice is connected to, which is empty when the invoice is generated directly.

**Comment by avillegasn** [comment]
That's true. It's fixed now.
