### ISSUE TITLE
Notice in unit price field

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#32]
There are few notices getting generated in Unit Price field. See screenshot:
![Screenshot 2019-04-04 at 5 42 54 PM](https://user-images.githubusercontent.com/7571618/55554748-3064b180-5701-11e9-920d-e776a7953d86.png)

**Comment by avillegasn** [comment]
Fixed in d166eb768b8cdfce6fc7f8388cf76e4aaae94ef6
